import NavBar from "../_root_components/NavBar"
import PortfolioNav from "./_portfolio_components/PortfolioNav"
import { PortfolioSettingProvider } from "./_settings"

export const metadata = {
    title: 'Portfolio',
    description: 'Generated by create next app',
}

export default function PortfolioLayout({ children }) {
    return (
        <div>
            <NavBar segment={'portfolio'} />
            <>
                <PortfolioNav />
                <PortfolioSettingProvider>
                    {children}
                </PortfolioSettingProvider>
            </>
        </div>
    )
}