import NavBar from '@/app/_root_components/NavBar'
import './globals.css'
import { poppins } from '@/assets/fonts'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-black text-white ${poppins.className} mx-20`}>
        <section className='flex flex-col h-screen'>
          <NavBar />
          {children}
        </section>
      </body>
    </html>
  )
}
