import NavBar from '@/app/_root_components/NavBar'
import './globals.css'
import { poppins, inter, satisfy } from '@/assets/fonts'


export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={`${poppins.variable} ${inter.variable} ${satisfy.variable}`}>
            <body className={`bg-black text-white font-poppins mx-20`}>
                {children}
            </body>
        </html>
    )
}
